#!/usr/bin/bash

set -euo pipefail

# Use SUDO_USER to get actual user because fpm after install scripts are run as root
sudo usermod -aG docker "$SUDO_USER"

if grep -qi "microsoft" /proc/version; then
  echo "Installing on WSL machine"

  echo "Set default web browser to WslView"
  su -c "xdg-settings set default-web-browser wslview.desktop" "$SUDO_USER"
else
  echo "Installing on Linux machine"

  echo "Set default web browser to firefox"
  su -c "xdg-settings set default-web-browser firefox.desktop" "$SUDO_USER"
fi