#!/usr/bin/bash

sudo groupadd docker
# Use SUDO_USER to get actual user because fpm after install scripts are run as root
sudo usermod -aG docker $SUDO_USER
echo "alias naksu2='/usr/lib/naksu2/Naksu2'" | sudo tee -a /etc/bash.bashrc > /dev/null
