#!/usr/bin/bash

TAG=ytl-linux-purge-deb

is_installed () {
    package=$1
    echo "Checking if package $package is installed"
    status=`dpkg-query -W --showformat='${Status}\n' $package 2>/dev/null |grep "install ok installed"`
    if [ $? -gt 0 ]; then
        return 0
    fi

    return 1
}

purge_package () {
    package=$1
    logger --tag=$TAG "Purging package $package"
    apt-get --yes purge $package
}

while IFS="" read -r line || [ -n "$line" ]
do
    package_name=`echo $line | sed 's|\s||g'`
    if [ -z "$package_name" ]; then
        continue
    fi

    if [[ "$package_name" =~ "#".* ]]; then
        continue
    fi

    is_installed $package_name
    if [ $? -gt 0 ]; then
        purge_package $package_name
    fi
done < /etc/ytl-linux-purge-deb.conf
