#!/usr/bin/bash

TAG=ytl-linux-purge-deb

is_installed () {
    package=$1
    echo "Checking if package $package is installed"
    status=`dpkg-query -W --showformat='${Status}\n' $package 2>/dev/null |grep "install ok installed"`
    if [ $? -gt 0 ]; then
        return 0
    fi

    return 1
}

purge_package () {
    package=$1
    logger --tag=$TAG "Purging package $package"
    apt-get --yes purge $package
}

stop_service () {
    service=$1

    logger --tag=$TAG "Stopping service $service"
    systemctl stop $service
    RESULT=$?
    if [ $RESULT -gt 0 ]; then
        logger --tag=$TAG "Stopping service $service failed with exit code $RESULT"
    fi

    logger --tag=$TAG "Disabling service $service"
    systemctl disable $service
    RESULT=$?
    if [ $RESULT -gt 0 ]; then
        logger --tag=$TAG "Disabling service $service failed with exit code $RESULT"
    fi
}

stop_services () {
    list_of_service_names=$1

    for this_service in ${list_of_service_names//,/ }; do
        stop_service $this_service
    done
}

while IFS="" read -r line || [ -n "$line" ]
do
    line_without_whitespaces=`echo $line | sed 's|\s||g'`

    package_name=`echo $line_without_whitespaces | awk -F':' '{print $1}'`
    list_of_service_names=`echo $line_without_whitespaces | awk -F':' '{print $2}'`

    if [ -z "$package_name" ]; then
        continue
    fi

    if [[ "$package_name" =~ "#".* ]]; then
        continue
    fi

    is_installed $package_name
    if [ $? -gt 0 ]; then
        if [ ! -z "$list_of_service_names" ]; then
            stop_services $list_of_service_names
        fi

        purge_package $package_name
    fi
done < /etc/ytl-linux-purge-deb.conf
