FROM --platform=linux/amd64 ubuntu:jammy
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get -y install wget fdisk libarchive-tools xorriso cd-boot-images-amd64
RUN mkdir /app && wget -O /app/ubuntu.iso https://releases.ubuntu.com/22.04/ubuntu-22.04.1-live-server-amd64.iso
COPY build-ytl-image /app/
COPY mangle-image /app/
COPY templates/ /app/templates/
