FROM --platform=linux/amd64 ubuntu:jammy
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get -y install wget fdisk libarchive-tools xorriso cd-boot-images-amd64
RUN mkdir /app
COPY build-ytl-image download-ubuntu-base-image /app/
COPY mangle-image /app/
COPY templates/ /app/templates/
