#!/bin/sh

set -e

# This script will be called with an argument pointing to
# an unpacked directory of the ISO image to be modified, and is free to
# add, modify or delete files therein.
#
# The main repository checkout is in the current working directory.

WORKDIR="$1"

# make our own ISOLINUX boot entry in place, substituting
# the URL where the clients will fetch the autoinstall configuration
sed "s|##AUTOINSTALL_URL##|$AUTOINSTALL_URL|" ytl.cfg.template > "$WORKDIR"/isolinux/ytl.cfg

# activate the entry
sed -i '/txt\.cfg/ iinclude ytl.cfg' "$WORKDIR"/isolinux/menu.cfg

# disable the default boot to live installation mode
sed -i 's/^ui /# ui/' "$WORKDIR"/isolinux/isolinux.cfg

# All done!
