#!/bin/sh

set -e

# This script will be called with an argument pointing to
# an unpacked directory of the ISO image to be modified, and is free to
# add, modify or delete files therein.
#
# The main repository checkout is in the current working directory.

WORKDIR="$1"

#########################################
# Step 1: legacy boot mode / ISOLINUX
#########################################

# make our own ISOLINUX boot entry in place, substituting
# the URL where the clients will fetch the autoinstall configuration
sed "s|##AUTOINSTALL_URL##|$AUTOINSTALL_URL|" templates/ytl-isolinux.cfg > "$WORKDIR"/isolinux/ytl.cfg

# activate the entry
sed -i '/txt\.cfg/ iinclude ytl.cfg' "$WORKDIR"/isolinux/menu.cfg

# disable the default boot to live installation mode
sed -i 's/^ui /# ui/' "$WORKDIR"/isolinux/isolinux.cfg

#########################################
# Step 2: UEFI boot mode / GRUB
#########################################

sed -i '/"Install Ubuntu Server"/iINCLUDE_YTL_MENU' "$WORKDIR"/boot/grub/grub.cfg
sed -i '/INCLUDE_YTL_MENU/r templates/ytl-grub.cfg' "$WORKDIR"/boot/grub/grub.cfg
sed -i '/INCLUDE_YTL_MENU/d' "$WORKDIR"/boot/grub/grub.cfg
sed -i "s|##AUTOINSTALL_URL##|$AUTOINSTALL_URL|" "$WORKDIR"/boot/grub/grub.cfg

# All done!
