#!/bin/sh

set -e

# This script will be called with an argument pointing to
# an unpacked directory of the ISO image to be modified, and is free to
# add, modify or delete files therein.
#
# The main repository checkout is in the current working directory.

WORKDIR="$1"

#########################################
# Step 2: UEFI boot mode / GRUB
#########################################

sed -i '/Install Ubuntu Server/iINCLUDE_YTL_MENU' "$WORKDIR"/boot/grub/grub.cfg
sed -i '/INCLUDE_YTL_MENU/r templates/ytl-grub.cfg' "$WORKDIR"/boot/grub/grub.cfg
sed -i '/INCLUDE_YTL_MENU/d' "$WORKDIR"/boot/grub/grub.cfg
sed -i "s|##AUTOINSTALL_URL##|$AUTOINSTALL_URL|" "$WORKDIR"/boot/grub/grub.cfg

# disable timeout to avoid installation loops and accidents
sed -i 's/timeout=[[:digit:]]\+/timeout=-1/' "$WORKDIR"/boot/grub/grub.cfg

# All done!
