[project]
name = "digabi2-examnet-bouncer"
dynamic = ["version"]
description = ""
requires-python = ">=3.12"
dependencies = ["Werkzeug==3.1.3", "zeroconf==0.148.0"]

[project.scripts]
digabi2-examnet-bouncer = "digabi2_examnet_bouncer.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/digabi2_examnet_bouncer/__init__.py"

[tool.pyright]
typeCheckingMode =  "basic"
