#!/usr/bin/env bash

set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <log-file> [output-html]"
  echo "  log-file    : exam-server-network-test-*.log generated by test-connections.sh"
  echo "  output-html : optional, defaults to <log-file>.html"
  exit 1
fi

log_file="$1"

if [[ ! -f "$log_file" ]]; then
  echo "Error: log file not found: $log_file" >&2
  exit 1
fi

output_html="${2:-${log_file}.html}"

title="YTL Exam Server - network connection diagnostics report"

# Extract local timestamp from the log, if present
local_time="$(grep -m1 'Time (local):' "$log_file" 2>/dev/null | sed 's/^[[:space:]]*Time (local):[[:space:]]*//')"

{
  echo "<!doctype html>"
  echo "<html lang=\"en\">"
  echo "<head>"
  echo "  <meta charset=\"utf-8\" />"
  echo "  <title>${title}</title>"
  echo "  <style>"
  echo "    body { font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 1.5rem; }"
  echo "    h1 { font-size: 1.6rem; margin-bottom: 0.5rem; }"
  echo "    h2 { font-size: 1.3rem; margin-top: 1.5rem; }"
  echo "    .meta { margin-bottom: 1rem; color: #555; }"
  echo "    table.summary { border-collapse: collapse; width: 100%; max-width: 960px; margin-bottom: 1.5rem; }"
  echo "    table.summary th, table.summary td { border: 1px solid #ddd; padding: 0.4rem 0.6rem; font-size: 0.9rem; }"
  echo "    table.summary th { background: #f0f0f0; text-align: left; }"
  echo "    tr.ok { background: #e7f7ea; }"
  echo "    tr.fail { background: #fbe9e9; }"
  echo "    .status-dot { font-size: 1rem; }"
  echo "    .status-ok { color: #2e7d32; }"
  echo "    .status-fail { color: #c62828; }"
  echo "    pre { background: #f7f7f7; padding: 1rem; border-radius: 4px; overflow-x: auto; }"
  echo "  </style>"
  echo "</head>"
  echo "<body>"
  echo "  <h1>${title}</h1>"
  echo "  <div class=\"meta\">"
  echo "    <div>Source log file: <code>${log_file}</code></div>"
  if [[ -n "$local_time" ]]; then
    echo "    <div>Test time (local): ${local_time}</div>"
  fi
  echo "  </div>"
  echo "  <h2>Summary</h2>"
  echo "  <table class=\"summary\">"
  echo "    <thead>"
  echo "      <tr><th>Status</th><th>Host</th><th>Port (outbound)</th><th>Description</th><th>DNS</th><th>TCP</th><th>HTTP</th></tr>"
  echo "    </thead>"
  echo "    <tbody>"
  awk '
    /^Host : / {
      if (host != "") {
        overall = "ok"
        if (dns ~ /FAIL/ || tcp ~ /FAIL/ || http ~ /FAIL/) {
          overall = "fail"
        }

        # escape HTML
        gsub(/&/, "\\&amp;", host); gsub(/</, "\\&lt;", host); gsub(/>/, "\\&gt;", host);
        gsub(/&/, "\\&amp;", desc); gsub(/</, "\\&lt;", desc); gsub(/>/, "\\&gt;", desc);
        gsub(/&/, "\\&amp;", dns);  gsub(/</, "\\&lt;", dns);  gsub(/>/, "\\&gt;", dns);
        gsub(/&/, "\\&amp;", tcp);  gsub(/</, "\\&lt;", tcp);  gsub(/>/, "\\&gt;", tcp);
        gsub(/&/, "\\&amp;", http); gsub(/</, "\\&lt;", http); gsub(/>/, "\\&gt;", http);
        gsub(/&/, "\\&amp;", port); gsub(/</, "\\&lt;", port); gsub(/>/, "\\&gt;", port);

        statusClass = (overall == "ok") ? "status-ok" : "status-fail";
        rowClass = (overall == "ok") ? "ok" : "fail";
        statusText = (overall == "ok") ? "OK" : "FAIL";
        dot = (overall == "ok") ? "&#9679;" : "&#9679;";

        printf "      <tr class=\"%s\"><td><span class=\"status-dot %s\">%s %s</span></td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>\n",
               rowClass, statusClass, dot, statusText, host, port, desc, dns, tcp, http;
      }
      host = substr($0, 8); desc=""; port=""; dns=""; tcp=""; http="";
    }
    /^Desc : / { desc = substr($0, 8); }
    /^Port : / { port = substr($0, 8); }
    /^DNS  : / { dns  = substr($0, 8); }
    /^TCP  : / { tcp  = substr($0, 8); }
    /^HTTP : / { http = substr($0, 8); }
    END {
      if (host != "") {
        overall = "ok"
        if (dns ~ /FAIL/ || tcp ~ /FAIL/ || http ~ /FAIL/) {
          overall = "fail"
        }

        gsub(/&/, "\\&amp;", host); gsub(/</, "\\&lt;", host); gsub(/>/, "\\&gt;", host);
        gsub(/&/, "\\&amp;", desc); gsub(/</, "\\&lt;", desc); gsub(/>/, "\\&gt;", desc);
        gsub(/&/, "\\&amp;", dns);  gsub(/</, "\\&lt;", dns);  gsub(/>/, "\\&gt;", dns);
        gsub(/&/, "\\&amp;", tcp);  gsub(/</, "\\&lt;", tcp);  gsub(/>/, "\\&gt;", tcp);
        gsub(/&/, "\\&amp;", http); gsub(/</, "\\&lt;", http); gsub(/>/, "\\&gt;", http);
        gsub(/&/, "\\&amp;", port); gsub(/</, "\\&lt;", port); gsub(/>/, "\\&gt;", port);

        statusClass = (overall == "ok") ? "status-ok" : "status-fail";
        rowClass = (overall == "ok") ? "ok" : "fail";
        statusText = (overall == "ok") ? "OK" : "FAIL";
        dot = (overall == "ok") ? "&#9679;" : "&#9679;";

        printf "      <tr class=\"%s\"><td><span class=\"status-dot %s\">%s %s</span></td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>\n",
               rowClass, statusClass, dot, statusText, host, port, desc, dns, tcp, http;
      }
    }
  ' "$log_file"
  echo "    </tbody>"
  echo "  </table>"
  echo "  <h2>Raw output</h2>"
  echo "  <pre>"
  # Escape HTML special chars and preserve line breaks
  awk '{
    gsub(/&/, "\\&amp;");
    gsub(/</, "\\&lt;");
    gsub(/>/, "\\&gt;");
    print $0;
  }' "$log_file"
  echo "  </pre>"
  echo "</body>"
  echo "</html>"
} >"$output_html"

echo "HTML report written to: $output_html"

