# Prevent NetworkManager from attempting to manage Docker's network devices,
# causing performance degradation and other incredibly obscure failure conditions
# when Abitti 2 server is running

# Docker's default network bridge network device
[device-docker-unmanaged]
match-device=interface-name:docker0
managed=0

# KTP bridge networks (public ytl0 and internal ytl1)
[device-ytl-unmanaged]
match-device=interface-name:ytl*
managed=0

# Docker-created virtual switches (veth)
[device-veth-unmanaged]
match-device=interface-name:veth*
managed=0
