#!/bin/bash

myname=${00##*/}
log() { /usr/bin/logger -p user.info -t "${myname}[$$]" "$*"; }

ETHTOOL=/sbin/ethtool

test -x $ETHTOOL || exit 0

IFACE=$1
ACTION=$2

[ "$IFACE" != "lo" ] || exit 0
[ "$ACTION" == "up" ] || exit 0

if [[ "$IFACE" =~ ^en ]] || [[ "$IFACE" =~ ^eth ]]; then
    ethtool -K $IFACE tso off
    log Setting TSO off for device $IFACE
else
    log Ignoring device $IFACE
fi
