#!/usr/bin/env bash

set -euo pipefail

# Copy from host volume for working, since it's read-only
cp -r deb-src/* .

# Run Makefile in package directory
make deb

# Copy built deb back to host volume
cp ./*.deb deb-src/
