#!/usr/bin/env bash

set -euo pipefail

REQUIRED_ENV_VARS=(
  NAME
  VERSION
  DESCRIPTION
)

for var in "${REQUIRED_ENV_VARS[@]}"; do
  if [[ -z "${!var}" ]]; then
    echo "Error: Required environment variable '$var' is not set"
    exit 1
  fi
done

FPM_FLAGS=(
  --force # Overwrite deb if it already exists
  --chdir deb-root/
  --input-type dir
  --output-type deb
  --architecture amd64
  --name "$NAME"
  --version "$VERSION"
  --description "$DESCRIPTION"
  --deb-no-default-config-files
  --maintainer 'abitti@ylioppilastutkinto.fi'
  --vendor 'Matriculation Examination Board'
  --url 'https://github.com/digabi/ytl-linux'
)

set -x
fpm "${FPM_FLAGS[@]}" "$@" .
