name: 'Examnet'

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-unit:
    name: Unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/ytl-linux-digabi2-examnet
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: packages/ytl-linux-digabi2-examnet/package-lock.json
      - name: Install Node.js dependencies
        run: npm ci --no-audit --no-fund
      - name: Run unit tests
        run: npm run test