on:
  push:
    tags:
    - 'v24.*'

name: Build and upload Ubuntu 24 image
jobs:
  build-and-upload:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
      - name: Build ytl-install-24.iso
        run: |
          just build-image-builder
          just build
      - name: Look up AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.2.2 # Immutable tag
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - name: Copy file with the AWS CLI
        run: |
          aws s3 cp ytl-install-24.iso s3://ytl-linux
